Viktoria stepanova
ivlytvynets/hw_lesson_2 pull request #5
Opened 2023-12-08 13:34 UTC by Viktoria2829

2023-12-09 22:45 UTC, Viktoria2829 reviewed
my homework 2

2023-12-11 09:28 UTC, ivlytvynets requested changes
Also, implement method print

2023-12-11 09:28 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +        return "Hello Bob";
method should have input parameter `String name` to greet by name

2023-12-11 09:28 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +    }
they do the same action as method `getDivide`, remove them

2023-12-11 09:28 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +    public static int getDivide(int a, int b) {
rename to `divide`

2023-12-11 09:28 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +
remove empty lines

2023-12-19 12:48 UTC, ivlytvynets commented
Need to implement method `print`

2023-12-19 13:00 UTC, ivlytvynets requested changes
треба реалізувати метод `print`. Передивіться README

2023-12-19 13:00 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +    public static String Name() {
назви методів - з маленької, а також починатися з дієслова: `getName` or `greet`. Але назва `getName` не підходить так як не відповідає логіці метода

2023-12-19 13:00 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +    public static int Divide(int a, int b) {
назва метода - з маленької

2023-12-19 16:11 UTC, ivlytvynets approved these changes

2023-12-19 16:11 UTC, closed without merging