Hey, here homework#2 Serhii Chumachenko.
ivlytvynets/hw_lesson_2 pull request #6
Opened 2023-12-10 11:52 UTC by DefaultHumanAI

2023-12-11 09:22 UTC, ivlytvynets requested changes

2023-12-11 09:22 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +  public static String print(String name){
this method should return nothing. It just prints into console

2023-12-11 09:22 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +    }
no need to use if-block, simplify your cide

2023-12-11 09:22 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +    }
remove if-else block, simplify your code as well

2023-12-11 10:48 UTC, DefaultHumanAI commented on src/main/java/com/lemon/school/Main.java
> +    }
В умові сказано що метод повертає ціле число, якщо я не перевірю чи більше число яке маємо ділити, в якийсь момент цілого не було. Якісь там як 0,423... інт обріже до 0 і все

2023-12-11 10:52 UTC, DefaultHumanAI commented on src/main/java/com/lemon/school/Main.java
> +  public static String print(String name){
Ви праві, але таке завдання, я його остаточно й не зрозумів. Написано передати в консоль результат роботи "greet" методу і щоб приймав строку, те й зробив. Не підскажете що малось на увазі в завданні, якщо це не коректно?

2023-12-13 00:24 UTC, DefaultHumanAI commented
Fixed

2023-12-19 12:42 UTC, ivlytvynets commented on src/main/java/com/lemon/school/Main.java
> +  public static String print(String name){
малось на увазі зберегти в окрему змінну результат `greet` методу, потім передати в параметр `print` і все)
Але в цілому все ок

2023-12-19 12:42 UTC, ivlytvynets approved these changes

2023-12-19 12:42 UTC, closed without merging